-- =============================================================================
-- NotDore — Tools catalog
-- Chạy một lần trong Supabase SQL Editor sau schema_v2.sql.
-- PostgreSQL tự chuyển tên bảng/cột không có dấu nháy về chữ thường.
-- =============================================================================

CREATE TABLE IF NOT EXISTS categories (
  category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE,
  description   TEXT
);

CREATE TABLE IF NOT EXISTS tools (
  tool_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_name   VARCHAR(255) NOT NULL,
  category_id BIGINT REFERENCES categories(category_id) ON DELETE SET NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS external_sources (
  source_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name VARCHAR(100) NOT NULL,
  source_type VARCHAR(50) NOT NULL,
  base_url    VARCHAR(500),
  icon_url    VARCHAR(500),
  CONSTRAINT external_sources_type_check
    CHECK (source_type IN ('file', 'video', 'repo', 'social', 'cloud'))
);

CREATE TABLE IF NOT EXISTS tool_links (
  link_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id      BIGINT NOT NULL REFERENCES tools(tool_id) ON DELETE CASCADE,
  source_id    BIGINT NOT NULL REFERENCES external_sources(source_id) ON DELETE RESTRICT,
  embed_url    VARCHAR(1000) NOT NULL,
  display_name VARCHAR(255),
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tool_links_url_check CHECK (embed_url ~* '^https?://')
);

CREATE TABLE IF NOT EXISTS tags (
  tag_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tool_tags (
  tool_id BIGINT NOT NULL REFERENCES tools(tool_id) ON DELETE CASCADE,
  tag_id  BIGINT NOT NULL REFERENCES tags(tag_id) ON DELETE CASCADE,
  PRIMARY KEY (tool_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_tools_category_id ON tools(category_id);
CREATE INDEX IF NOT EXISTS idx_tool_links_tool_active ON tool_links(tool_id, is_active);
CREATE INDEX IF NOT EXISTS idx_tool_tags_tag_id ON tool_tags(tag_id);

-- Dùng chung hàm trigger của schema_v2; CREATE OR REPLACE giúp migration chạy độc lập.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tools_updated_at ON tools;
CREATE TRIGGER trg_tools_updated_at
  BEFORE UPDATE ON tools
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- API Vercel hiện dùng SUPABASE_ANON_KEY: chỉ công khai quyền đọc catalog.
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE external_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE tool_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE tool_tags ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON categories, tools, external_sources, tool_links, tags, tool_tags TO anon;

DROP POLICY IF EXISTS "Public can read tool categories" ON categories;
DROP POLICY IF EXISTS "Public can read tools" ON tools;
DROP POLICY IF EXISTS "Public can read external sources" ON external_sources;
DROP POLICY IF EXISTS "Public can read active tool links" ON tool_links;
DROP POLICY IF EXISTS "Public can read tags" ON tags;
DROP POLICY IF EXISTS "Public can read tool tags" ON tool_tags;

CREATE POLICY "Public can read tool categories" ON categories FOR SELECT TO anon USING (true);
CREATE POLICY "Public can read tools" ON tools FOR SELECT TO anon USING (true);
CREATE POLICY "Public can read external sources" ON external_sources FOR SELECT TO anon USING (true);
CREATE POLICY "Public can read active tool links" ON tool_links FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "Public can read tags" ON tags FOR SELECT TO anon USING (true);
CREATE POLICY "Public can read tool tags" ON tool_tags FOR SELECT TO anon USING (true);
